version: '2.1'

services:

  client:
    container_name: client
    build: ./client
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '5000:5000'

  server:
    container_name: server
    build: ./server
    volumes:
      - './server:/usr/src/app'
      - './server/package.json:/usr/src/package.json'
    ports:
      - '8080:8080'
